DELETE FROM DETALLE_MEMBRESIA;
DELETE FROM EVENTO;
DELETE FROM JORNADA;
DELETE FROM USUARIO WHERE USUARIO.USUARIO <> 'CVivar98';
DELETE FROM TEMPORADA;
DELETE FROM DEPORTE;

drop trigger INSERT_EVENT;

SELECT * FROM DETALLE_MEMBRESIA;
SELECT * FROM USUARIO;
SELECT * FROM TEMPORADA;
SELECT * FROM JORNADA;
SELECT * FROM DEPORTE;
SELECT *  FROM EVENTO;
SELECT *  FROM prediccion;


update USUARIO set USUARIO.NOMBRE='Esteban'
WHERE USUARIO.USUARIO = 'CVivar98'

SELECT ID_JORNADA
    FROM JORNADA
    INNER JOIN TEMPORADA
    ON JORNADA.ID_TEMPORADA=TEMPORADA.ID_TEMPORADA
    WHERE JORNADA.NOMBRE = 'J1'
    AND TEMPORADA.NOMBRE='2019-Q2';

SELECT DEPORTE.ID_DEPORTE
    FROM DEPORTE
    WHERE DEPORTE.NOMBRE = 'tennis';



iNSERT INTO EVENTO ("LOCAL", VISITANTE,FECHA, MARCADOR_LOCAL, MARCADOR_VISITA, ID_JORNADA, ID_DEPORTE)
VALUES  ('Stefa Kissick', 'Cacilie Peoples', TO_DATE('02/03/2018 20:33','dd/mm/yyyy hh24:mi'), 6, 2, 2690, 34);