
DELETE FROM PREDICCION;          
    ALTER TABLE PREDICCION MODIFY(ID_PREDICCION GENERATED AS IDENTITY (START WITH 1));
    DELETE FROM DETALLE_MEMBRESIA;
    ALTER TABLE DETALLE_MEMBRESIA MODIFY(ID_DETALLE GENERATED AS IDENTITY (START WITH 1));    
    DELETE FROM EVENTO;
    ALTER TABLE EVENTO MODIFY(ID_EVENTO GENERATED AS IDENTITY (START WITH 1));   
    DELETE FROM JORNADA;
    ALTER TABLE JORNADA MODIFY(ID_JORNADA GENERATED AS IDENTITY (START WITH 1));   
    DELETE FROM USUARIO WHERE USUARIO.USUARIO <> 'CVivar98';
    ALTER TABLE USUARIO MODIFY(ID_USUARIO GENERATED AS IDENTITY (START WITH 2));   
    DELETE FROM TEMPORADA;
    ALTER TABLE TEMPORADA MODIFY(ID_TEMPORADA GENERATED AS IDENTITY (START WITH 1));  
    DELETE FROM DEPORTE;
    ALTER TABLE DEPORTE MODIFY(ID_DEPORTE GENERATED AS IDENTITY (START WITH 1));   
SELECT count(*) FROM DETALLE_MEMBRESIA;
    SELECT count(*) FROM USUARIO;
    SELECT count(*) FROM TEMPORADA;
    SELECT count(*) FROM JORNADA;
    SELECT count(*) FROM DEPORTE;
    SELECT count(*)  FROM EVENTO;
    SELECT count(*)  FROM prediccion;
SELECT * FROM DETALLE_MEMBRESIA;
    SELECT * FROM USUARIO;
    SELECT * FROM TEMPORADA;
    SELECT * FROM JORNADA;
    SELECT * FROM DEPORTE;
    SELECT *  FROM EVENTO;
    SELECT *  FROM prediccion;
--Predicciones de cada temporada

SELECT COUNT(P.ID_PREDICCION) C,T.ID_TEMPORADA
 
FROM PREDICCION P

INNER JOIN EVENTO E
ON P.ID_EVENTO=E.ID_EVENTO

INNER JOIN JORNADA J
ON J.ID_JORNADA = E.ID_JORNADA

INNER JOIN TEMPORADA T
ON J.ID_TEMPORADA =T.ID_TEMPORADA

INNER JOIN TEMPORADA T
ON J.ID_TEMPORADA=T.ID_TEMPORADA

GROUP BY T.ID_TEMPORADA 
ORDER BY T.ID_TEMPORADA ASC


--SUMA DE PUNTOS DE PREDICCIONES HECHAS POR USUARIO POR TEMPORADA
SELECT U.ID_USUARIO,count(P.id_prediccion) C,T.ID_TEMPORADA
 
FROM PREDICCION P

INNER JOIN USUARIO U 
ON P.ID_USUARIO = U.ID_USUARIO

INNER JOIN EVENTO E
ON P.ID_EVENTO=E.ID_EVENTO

INNER JOIN JORNADA J
ON J.ID_JORNADA = E.ID_JORNADA

INNER JOIN TEMPORADA T
ON J.ID_TEMPORADA =T.ID_TEMPORADA

INNER JOIN TEMPORADA T
ON J.ID_TEMPORADA=T.ID_TEMPORADA

GROUP BY T.ID_TEMPORADA,U.ID_USUARIO,u.USUARIO
ORDER BY T.ID_TEMPORADA ASC,SUM(P.PUNTAJE) DESC




--RANKING PUNTOS DE PREDICCIONES POR TEMPORADA(NO MODIFICAR)

SELECT RANKING,PUNTOS,TEMPORADA
	FROM (
SELECT TEMPORADA,PUNTOS,(DENSE_RANK() OVER(PARTITION BY TEMPORADA 
            ORDER BY PUNTOS DESC)) AS RANKING
			FROM(
                    SELECT  SUM(P.PUNTAJE) PUNTOS,
                                    T.ID_TEMPORADA TEMPORADA
                    FROM PREDICCION P

                    INNER JOIN USUARIO U ON P.ID_USUARIO = U.ID_USUARIO      
                    INNER JOIN EVENTO E ON P.ID_EVENTO=E.ID_EVENTO                               
                    INNER JOIN JORNADA J ON J.ID_JORNADA = E.ID_JORNADA
                    INNER JOIN TEMPORADA T ON J.ID_TEMPORADA =T.ID_TEMPORADA
                    

                    GROUP BY 
                        T.ID_TEMPORADA,
                        U.ID_USUARIO
                        
                    ORDER BY                         
                        T.ID_TEMPORADA ASC,
                        SUM(P.PUNTAJE) DESC
                    
                )
        )
    WHERE RANKING =2;




--REPORTE 3
------------------------
SELECT
    RANKING,
    MEMBERS,
    COUNT(*)
FROM
    (
        SELECT
            MEMBERS,(
                DENSE_RANK() OVER(
                    PARTITION BY TEMPORADA
                    ORDER BY
                        PUNTOS DESC
                )
            ) AS RANKING
        FROM(
                SELECT
                    SUM(P.PUNTAJE) PUNTOS,
                    T.ID_TEMPORADA TEMPORADA,
                    M.NOMBRE MEMBERS
                FROM
                    PREDICCION P
                    INNER JOIN USUARIO U ON P.ID_USUARIO = U.ID_USUARIO
                    INNER JOIN DETALLE_MEMBRESIA DM ON DM.ID_USUARIO = U.ID_USUARIO
                    INNER JOIN TEMPORADA T ON T.ID_TEMPORADA = DM.ID_TEMPORADA
                    INNER JOIN JORNADA J ON J.ID_TEMPORADA = T.ID_TEMPORADA
                    INNER JOIN EVENTO E ON E.ID_EVENTO = P.ID_EVENTO
                    AND E.ID_JORNADA = J.ID_JORNADA
                    INNER JOIN MEMBRESIA M ON M.ID_MEMBRESIA = DM.ID_MEMBRESIA
                GROUP BY
                    U.ID_USUARIO,
                    M.NOMBRE,
                    T.ID_TEMPORADA
            )
    )
GROUP BY
    RANKING,
    MEMBERS
HAVING
    RANKING <= 3
ORDER BY
    RANKING ASC


------------------------------------


update USUARIO set USUARIO.NOMBRE='Esteban'
WHERE USUARIO.USUARIO = 'CVivar98'

SELECT ID_JORNADA
    FROM JORNADA
    INNER JOIN TEMPORADA
    ON JORNADA.ID_TEMPORADA=TEMPORADA.ID_TEMPORADA
    WHERE JORNADA.NOMBRE = 'J1'
    AND TEMPORADA.NOMBRE='2019-Q2';

SELECT DEPORTE.ID_DEPORTE
    FROM DEPORTE
    WHERE DEPORTE.NOMBRE = 'tennis';



iNSERT INTO EVENTO ("LOCAL", VISITANTE,FECHA, MARCADOR_LOCAL, MARCADOR_VISITA, ID_JORNADA, ID_DEPORTE)
VALUES  ('Stefa Kissick', 'Cacilie Peoples', TO_DATE('02/03/2018 20:33','dd/mm/yyyy hh24:mi'), 6, 2, 2690, 34);