DELETE FROM DETALLE_MEMBRESIA;
DELETE FROM JORNADA;
DELETE FROM USUARIO WHERE USUARIO.USUARIO <> 'CVivar98';
DELETE FROM TEMPORADA;
DELETE FROM DEPORTE;

SELECT * FROM DETALLE_MEMBRESIA;
SELECT * FROM USUARIO;
SELECT * FROM TEMPORADA;
SELECT * FROM JORNADA;
SELECT * FROM DEPORTE;





