CREATE OR REPLACE TRIGGER INSERT_USER
BEFORE INSERT ON USUARIO 
FOR EACH ROW 
DECLARE
NOW NUMBER:=EXTRACT(YEAR FROM  SYSDATE);
BIRTH NUMBER:=EXTRACT(YEAR FROM :NEW.NACIMIENTO);
COUNTER NUMBER;

BEGIN
SELECT COUNT(*) INTO COUNTER FROM USUARIO WHERE USUARIO = :NEW.USUARIO;
IF ((NOW - BIRTH)<18) 
then RAISE_APPLICATION_ERROR(-20001, 'ERROR EDAD'); 
END IF;

IF (COUNTER != 0) 
then RAISE_APPLICATION_ERROR(-20001, 'ERROR USUARIO'); 
END IF;

IF (NOT REGEXP_LIKE(:NEW.EMAIL, '^(\S+)\@(\S+)\.(\S+)$'))
THEN RAISE_APPLICATION_ERROR(-20001, 'ERROR CORREO'); 
END IF;

IF NOT( REGEXP_LIKE(:NEW.CLAVE, '^.*[0-9]', 'c')
AND REGEXP_LIKE(:NEW.CLAVE, '^.*[a-z]','c')
AND REGEXP_LIKE(:NEW.CLAVE, '^.*[A-Z]','c')
AND REGEXP_LIKE(:NEW.CLAVE,'(\S){9,}$', 'c'))
THEN RAISE_APPLICATION_ERROR(-20001, 'ERROR CLAVE'); 
END IF;
END;
